app:
  name: conv-app
  replicas: 1
  components: frontend
  image: "antonlarichev/conv-app"
  tag: "1.2"
  port: 80
  limits:
    memory: "512Mi"
    cpu: "250m"
  config:
    name: vitedomain-config
    key: VITE_DOMAIN