apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-deployment"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.app.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.app.components }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            limits: {{ .Values.app.limits | toYaml | nindent 14 }}
          env:
            - name: {{ .Values.app.config.key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.config.name }}
                  key: {{ .Values.app.config.key }}

