apiVersion: v1
kind: Service
{{- with .Values.api }}
metadata:
  name: {{ .name }}-clusterip
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      protocol: TCP
  selector:
    components: {{ .components }}
{{- end -}}