apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbit.name }}-secret
type: Opaque
data:
  SEED_USERNAME: {{ .Values.rabbit.user | b64enc | quote}}
  SEED_USER_PASSWORD: {{ .Values.rabbit.pass | b64enc | quote }}
